### ISSUE TITLE
Access to Serial flash memory on MKRWAN1310 fails under core v. 1.8.11

### ISSUE THREAD

**Issue by terryzar** [arduino/ArduinoCore-samd#594] opened 2021-01-14 20:49 UTC
Using the SerialFlash library, accessing the on board serial flash memory works fine under Arduino SAMD Core library v1.8.10.  After upgrade to 1.8.11 access to the on board flash memory ceases.   I have not yet had time to analyze this, just rolled back to 1.8.10 and functions again.

**Comment by rocketscream** [comment] 2021-02-24 14:01
Same here and even if it worked with 1.8.10, it seems the bus clock has been set slower as default.

**Comment by facchinm** [comment] 2021-04-12 07:02
Closing as duplicate of #593 , fixed by https://github.com/arduino/ArduinoCore-samd/pull/622

**Closed by facchinm** 2021-04-12 07:02 UTC
